# Generated by Django 5.2.9 on 2025-12-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
