# Generated by Django 5.2.9 on 2025-12-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notes_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
