# Generated by Django 5.2.9 on 2025-12-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_alter_notes_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
