# Generated by Django 5.2.9 on 2025-12-04 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_notes_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='text',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator('[a-zA-Z0-9]*$', 'Only alphanumerics allowed')]),
        ),
    ]
